spring.application.name=Oauth2
spring.security.oauth2.client.registration.github.client-id=Ov23liJyW0tH9zuw8TfO
spring.security.oauth2.client.registration.github.client-secret=feb5d58b1279a7e5e2db096a917b2dca0b197291

